// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odqusjfkoysubywazqnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcXVzamZrb3lzdWJ5d2F6cW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTk3OTAsImV4cCI6MjA2ODE3NTc5MH0.kQdrx0SVBu63LFRsXqC7Dzqn1VLRMC-b3qVoleRZ5gY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});